### ISSUE TITLE
hovering of the text

### ISSUE THREAD

**Issue by Arraxx** [fluid-project/infusion-docs#152]
### Screenshot:
![Screenshot from 2020-02-23 14-14-25](https://user-images.githubusercontent.com/54955755/75109168-15679c80-5647-11ea-84cc-c49eec1fbfeb.png)
 
### Additional context:
i would like to take this issue

**Comment by jobara** [comment]
@coderbabu10 could you please explain why it is unnecessary.

**Comment by coderbabu10** [comment]
as we can make it more attractive by just having an underline or give simple hover @jobara

**Comment by jobara** [comment]
@coderbabu10 to be clear, you aren't saying that modifying the styling, that is providing a visual indication, on hover is necessary. Rather you are suggesting that particular style used for the hover indication should be modified. Is that correct?

Assuming the latter is what you are saying, please notice that an underline is already used to indicate which section is open. Notice the underline under "Infusion" in your screen shot. It would be confusing if an underline is provided both to indicate that a section is open and be used as a hover style. 

Could you explain more about about what you mean by "simple hover"? 

Also if you can expand on why the current implementation appears less professional, or other issues with the visual presentation for the hover effect, that might help with narrowing down on a path to take.

**Comment by coderbabu10** [comment]
no sir i am saying that we can just modify the hovering of the text just removing the background white color appears when the hover takes place as removing the yellow box around and just adding the yellow line down the text can looks more good @jobara

**Comment by coderbabu10** [comment]
it will look like this when changed 
![Screenshot from 2020-02-24 21-54-30](https://user-images.githubusercontent.com/54955755/75170595-5bf4ee00-5750-11ea-838f-2cec5e2a81bb.png)
and sorry sir for using that unnecessary word before

**Comment by coderbabu10** [comment]
@jobara

**Comment by jobara** [comment]
@coderbabu10 thanks for the example. However, in an earlier response I mentioned that the underline is already used to indicate that the section is open. By moving it to identify hover/focus we no longer have an indication for which section is open.

Going back to the issue you filed, I do agree that the hover styling can be improved. For example the colour contrast during the hover styling does not conform to [wcag AA](https://www.w3.org/TR/WCAG21/#contrast-minimum) specifications. Improving the colour contrast is something that should be done. 

Do you have any further insights or suggestions about the hover styling. We can pass these along to the designers to consider ways to improve them.

**Comment by coderbabu10** [comment]
1.we can do changes like making the text to yellow when the cursor goes to it, right now which is blue.
2.when the cursor comes to the text then the underline will appear not before that 
i think this is simple and looks much better.
@jobara

**Comment by jhung** [comment]
@coderbabu10 can you fork this repository and make changes in a branch demonstrating your solution? We can then discuss this further, especially making sure that your changes meet the colour contrast requirements for [W3C WCAG AA web accessibility compliance](https://www.w3.org/TR/WCAG21/#contrast-minimum).

When making code contributions, please see ["Coding and Commit Standards"](https://wiki.fluidproject.org/display/fluid/Coding+and+Commit+Standards#CodingandCommitStandards-UsingBranches) guide for this project.

**Comment by jobara** [comment]
It appears that the hover styling has a contrast ratio of 3.44 which doesn't meet WCAG 2.0 AA standards. We should look at improving this.

**Comment by greatislander** [comment]
I'm closing this in favour of #192.
