### ISSUE TITLE
Add button to search input

### ISSUE THREAD

**Issue by Arraxx** [fluid-project/infusion-docs#153]
### screenshot: 
![Screenshot from 2020-02-23 14-17-52](https://user-images.githubusercontent.com/54955755/75109229-8f982100-5647-11ea-8978-4676372c9e4e.png)

### additional context:
i would like to take this issue,

**Comment by coderbabu10** [comment]
@jobara

**Comment by jhung** [comment]
Thanks @coderbabu10. Can you create a branch in your fork with these changes so I can see what you are suggesting?

In your solution can you keep in mind web accessibility practices such as keyboard accessibility, colour contrast ([you can use this tool to help](https://developer.paciellogroup.com/resources/contrastanalyser/)), and [alt text for a functional image](https://www.w3.org/WAI/tutorials/images/functional/). This guide may be useful too ["Quick-and-Dirty Website Accessibility Tests"](https://wiki.fluidproject.org/display/fluid/Quick-and-Dirty+Website+Accessibility+Tests+-+and+Fixes).
