### ISSUE TITLE
Hover in Logo

### ISSUE THREAD

**Issue by Arraxx** [fluid-project/infusion-docs#155]
I think there shouldn't be hover for the logo of infusion

**Comment by jobara** [comment]
@coderbabu10 you'll need to provide more information here. Steps to reproduce, screen shot if possible, details about why it is an issue and etc.

**Comment by coderbabu10** [comment]
i think the logo doesn't needs any hover.
what are your views ? @jobara 
![Screenshot from 2020-02-28 12-53-20](https://user-images.githubusercontent.com/54955755/75519565-82a17600-5a29-11ea-80ce-07b845dbbb0e.png)

**Comment by jobara** [comment]
@jhung any thoughts?

**Comment by coderbabu10** [comment]
i think that making the logo not hover would be a better option from my views i think that hovering of the logo is not required as the user knows that the clicking of the logo will send them to the main page.

**Comment by jobara** [comment]
Hover styling tends to help with accessibility as it helps with additional visual cues; for example which elements are interactive.
