### ISSUE TITLE
the elements under the show preference are not properly displaying.

### ISSUE THREAD

**Issue by Arraxx** [fluid-project/infusion-docs#159]
## Screenshots:
![Screenshot from 2020-03-03 00-35-58](https://user-images.githubusercontent.com/54955755/75709081-04262c00-5ce8-11ea-8a1a-9efcc2ed2afe.png)

![Screenshot from 2020-03-03 00-36-16](https://user-images.githubusercontent.com/54955755/75709034-f2dd1f80-5ce7-11ea-8560-0fc32ae5767b.png)

## additional context:
I would like to take this issue.

**Comment by jobara** [comment]
@coderbabu10 could you explain more about what you mean by "we can also see that the arrows are not properly aligned it is slightly upwards." 

Some of the panels are too wide for the screen at small sizes, requiring the horizontal scroll. I believe this is the issue you are mentioning when you say "the contrast section it is not properly fitting inside it".  What are your thoughts on how this could be improved while at the same time maintaining enough separation and size of controls to be suitable for touch interactions on mobile devices.

**Comment by coderbabu10** [comment]
the arrow is slightly up as it should be in the center from right side then it will be more good we can make this change by simply adding the height.

i have just made some change you can see:
![Screenshot from 2020-03-03 23-33-15](https://user-images.githubusercontent.com/54955755/75805445-df918900-5da7-11ea-898a-dda4f0f24665.png)
## or
we can do one more thing 
![Screenshot from 2020-03-03 23-36-33](https://user-images.githubusercontent.com/54955755/75805474-ee783b80-5da7-11ea-9769-a289e613a2b5.png)
like in above image there is number we can add the color segment in it and instead of "+" and "-" we can add the arrow buttons 
What you think? @jobara

**Comment by jobara** [comment]
Regarding the arrow, I believe you are referring to the  left "<" and right ">" arrows for navigating between panels. They are actually intended to be inline with the heading, not centred within the panel. 

Regarding the alternate alternative example using the stepper, I'm not sure if that interaction helps. The current options act as a preview and quickly display all possible options. Having a stepper would require that the user selects each option one by one and not have any clear idea which one would be next. A carousel might make more sense, but they can be complicated at times and also limit the visible options.

**Comment by coderbabu10** [comment]
yes sir, i actually found that out but making the arrows in centre will be much better as it will look more proper that way  what you think?
and for the contrast part i think we should have a look for it in how we can make some changes to look it more proper @jhung @jobara

**Comment by jobara** [comment]
@coderbabu10 you are welcome to suggest some design changes, which we can review/discuss/consider.

**Comment by coderbabu10** [comment]
okay sir @jobara 
and one more thing sir i wanted to talk to you for the project of gsoc 2020 "Refactor and Automate Infusion Documentation" can you please explain me a bit more and what things i can start doing for the same.
Thank you.

**Comment by jobara** [comment]
@coderbabu10 this wouldn't be the correct place to talk about that. Could you please send your specific questions to the [fluid-work mailing list](https://lists.idrc.ocad.ca/mailman/listinfo/fluid-work
).

**Comment by coderbabu10** [comment]
sir, i tried doing it but i am not getting the request confirmation mail that's why i am having difficulties to communicate with you.
@jobara

**Comment by jobara** [comment]
@coderbabu10 you can try the fluid-work IRC channel ( https://wiki.fluidproject.org/display/fluid/IRC+Channel )

**Comment by jobara** [comment]
The issues mentioned here are really issues with UI Options. I've filed a new issue ([FLUID-6616](https://issues.fluidproject.org/browse/FLUID-6616)) against UI Options to examine the design of wide panels when on narrow windows/screens.
