### ISSUE TITLE
proper placement of components in the search page.

### ISSUE THREAD

**Issue by Arraxx** [fluid-project/infusion-docs#160]
## description :
the search page is not proper we can make it to the full page and also make the footer of full size that it covers the whole page.

## screenshots:
![Screenshot from 2020-03-03 23-13-55](https://user-images.githubusercontent.com/54955755/75804293-c1c32480-5da5-11ea-8630-fdb101cda179.png)

## additional text:
i would like to take this up

**Comment by jobara** [comment]
@coderbabu10 I'm not sure from your description what the actual issue is. Could you please elaborate in more detail and why making the change would improve things?

**Comment by coderbabu10** [comment]
as sir now in the left side it is all blank and i dont think we can add any stuff there so it would me more appropriate to make the page of full size so it will look more good,for better user interface.

**Comment by jobara** [comment]
I believe the issue being raised here is that the left nav is blank on the search page. The left nav is populated based on the section/category (e.g. Infusion, Tutorials, Components). It seems that removing the left nav would be the most appropriate for this current design.

**Comment by greatislander** [comment]
@jobara This can be resolved as part of #191.
