### ISSUE TITLE
adding of the social media buttons in footer

### ISSUE THREAD

**Issue by Arraxx** [fluid-project/infusion-docs#161]
## Enhancement:
we can add some social  media buttons in the footer so the user can easily access to the other social platforms by just clicking the buttons.

## additional text:
i would like to take this issue.

**Comment by coderbabu10** [comment]
@jobara @jhung please have a look and give your suggestions i think we can even add the address,contact number in the footer like the fluid site

**Comment by coderbabu10** [comment]
We can do one thing that in the left side we can add information about the site with the logo as it will look great for the user and then we can add the address on the right side with the small logo of the social media sites just below it.

**Comment by jobara** [comment]
@coderbabu10 I'm not sure that the documentation site needs this at the moment. Perhaps it could be something to consider in the future.

**Comment by coderbabu10** [comment]
okay @jobara
