### ISSUE TITLE
improvement of the accessibilty of the Website

### ISSUE THREAD

**Issue by coderbabu10** [fluid-project/infusion-docs#162]
we can add many different features for the improvement of accessibility of the Website as it will be good for all kind of users to easily access the website and work.
what are your views @jobara @jhung ?

**Comment by jobara** [comment]
@coderbabu10 we definitely want all of our work to be accessible and inclusive. However, for this issue you need to be specific about what you would like to add/change. If there are multiple new features, enhancements, or bugs. You'll need to file a specific bug or enhance request for each.
