### ISSUE TITLE
Adding Previous and Next button above footer

### ISSUE THREAD

**Issue by apshada** [fluid-project/infusion-docs#163]
![imageedit_5_6726829225](https://user-images.githubusercontent.com/49001649/76320480-c4be9780-6306-11ea-93ec-04b25bd59814.jpg)

**Feature**
Adding of previous and next button at bottom of the web page above footer such that surfing between pages become easier for user

**Comment by coderbabu10** [comment]
Hey @apshada i think we are having all the components in the left side and can easily be accessible so we should not need this and if we want next and previous buttons we can use the arrow buttons i think it will be much more attractive for the user
what do you think?  @jobara

**Comment by jobara** [comment]
It's something we can consider, possibly after the site back end changes. It needs more design thinking before we settle on implementing something like this though.

**Comment by apshada** [comment]
@jobara   i would like to work on this, will be making some interactive components buttons

**Comment by jobara** [comment]
@apshada what I was saying above is that we need to think about the design aspects before implementing any changes. Also at this point with the project to change the back end of the system, it isn't a good time to be implementing front end changes and redesigns. This is something we can consider in the future, but not something to focus on at the moment.
