### ISSUE TITLE
Hovering action for link

### ISSUE THREAD

**Issue by apshada** [fluid-project/infusion-docs#164]
![2 4](https://user-images.githubusercontent.com/49001649/76347472-ba16f900-632c-11ea-9245-f3c203746980.png)
**Issue**
Contrast does not have any hovering action on Link as shown above
![2 3](https://user-images.githubusercontent.com/49001649/76347479-bc795300-632c-11ea-91ad-16909c7a207d.png)

**Comment by jobara** [comment]
The "Grey on White", "Grey on Dark" and "Black on Brown" contrast are not providing any hover styling for hovering over links.
