### ISSUE TITLE
Search written in place holder.

### ISSUE THREAD

**Issue by Arraxx** [fluid-project/infusion-docs#165]
I think we can add a placeholder written search on it as it will good for the user.
We can link issue #153 .

**Comment by coderbabu10** [comment]
what are your views? @jobara @jhung

**Comment by jobara** [comment]
@coderbabu10 sorry, I'm not sure what this issue about. Could you please provide more details?

**Comment by coderbabu10** [comment]
before:
![Screenshot from 2020-03-11 18-44-39](https://user-images.githubusercontent.com/54955755/76420690-85f11600-63c8-11ea-95f7-a93643402266.png)
After:
![Screenshot from 2020-03-11 18-46-01](https://user-images.githubusercontent.com/54955755/76420750-9d300380-63c8-11ea-967b-40ce25ce571f.png)

as now Search will also be written in the box as it will look more good. :)

**Comment by coderbabu10** [comment]
and when we try to write something in it,then it will disappear.

**Comment by jobara** [comment]
@coderbabu10 okay, thanks, you are suggesting we add placeholder text to the search input field.

**Comment by coderbabu10** [comment]
Yes @jobara

**Comment by coderbabu10** [comment]
should i send a pr for the same? @jobara

**Comment by jobara** [comment]
@coderbabu10 if you want to work on an issue related to search, you may want to look at this https://issues.fluidproject.org/browse/FLUID-6476

**Comment by apshada** [comment]
@jobara  can i work on this issue?

**Comment by greatislander** [comment]
I'm closing this as the more signification issue (lack of accessible label) has been addressed in #190.
