### ISSUE TITLE
giving link title in footer for better accessibility.

### ISSUE THREAD

**Issue by Arraxx** [fluid-project/infusion-docs#168]
## screenshots:
![Screenshot from 2020-03-12 20-46-12](https://user-images.githubusercontent.com/54955755/76536590-8fe74780-64a2-11ea-8765-795f613a6823.png)
## additional text:
i would like to work on this issue

**Comment by jobara** [comment]
The links, as is, seem to provide enough information/context about what they are for. I'm going to close for now, but we can explore this further if necessary.
