### ISSUE TITLE
Use Eleventy navigation plugin to generate the sidebar

### ISSUE THREAD

**Issue by greatislander** [fluid-project/infusion-docs#191]
## Is your feature request related to a problem?

Currently the sidebar navigation is generated from a manually-maintained JSON manifest. 

## Describe the solution you'd like

This process can be improved by using Eleventy's official [navigation](https://www.11ty.dev/docs/plugins/navigation/) plugin to embed navigation structure data directly into documentation pages and make the sidebar easier to maintain as documentation is moved or changed.

## Describe alternative solutions you've considered

Not applicable.

## Additional context or notes

 I've already implemented this on both the [Inclusive Learning Design Handbook](https://github.com/fluid-project/docs-inclusive-learning) and [Inclusive Design Guide](https://github.com/inclusive-design/guide.inclusivedesign.ca/) sites, which were once set up the same way.

**Comment by greatislander** [comment]
See also: https://github.com/fluid-project/infusion-docs/issues/160

**Comment by cindyli** [comment]
Resolved by https://github.com/fluid-project/infusion-docs/pull/196

**Comment by greatislander** [comment]
@cindyli I'd like to keep this open for further work.
