### ISSUE TITLE
A single header id in the docs does not match what GitHub generates

### ISSUE THREAD

**Issue by jobara** [fluid-project/infusion-docs#225]
## Describe the bug

The heading for fluid.log in CoreAPI.html produces a different anchor on GitHub than in our rendered docs.

The text of the heading is: `fluid.log([logLevel, arg1, ... argn])`.  GitHub generates the header ID as "fluidlogloglevel-arg1--argn".
The new combination of markdown-it and [markdownit-anchor](https://www.npmjs.com/package/markdown-it-anchor) generates the ID as "fluidlogloglevel-arg1-argn" (note the single dash between "arg1" and "argn").

### To reproduce

Link on the docs site: https://docs.fluidproject.org/infusion/development/coreapi#fluidlogloglevel-arg1-argn
Link in GitHub: https://github.com/fluid-project/infusion-docs/blob/main/src/documents/CoreAPI.md#fluidlogloglevel-arg1--argn

### Expected behavior

The header IDs are the same so that the page anchors will be identical. This is important so that internal references will work when viewing the documentation on the website or in GitHub.

## Additional context or notes

Originally filed as [FLUID-6207](https://issues.fluidproject.org/browse/FLUID-6207)

**Comment by amb26** [comment]
Do we have a route to doing something about this? It seems like it might require forking a number of packages. I'd generally resigned myself to having internal references not work within GitHub which as the original issue reports has not worked for years.

**Comment by jobara** [comment]
@amb26 as you mention one option is to not enforce/expect internal references to work on GitHub. And then we just mark this as won't fix and close it. 

Another thing to consider is if we want to keep maintaining links with Markdown files. At the moment we do some processing to convert the links to point at the related html file during build. I suppose a similar step could be taken for this case where we do some processing at build to replace `--` with `-`.

**Comment by greatislander** [comment]
I saw this issue and found an easy way to resolve it without any post-processing or other hacks via the [github-slugger](https://github.com/Flet/github-slugger) package.
