### ISSUE TITLE
Uses of &lt; and &gt; in headers are turned into tags

### ISSUE THREAD

**Issue by greatislander** [fluid-project/infusion-docs#231]
## Describe the bug

In the IoC References page ( https://docs.fluidproject.org/infusion/development/IoCReferences#examples-of-componentrefpath-to-member ), some unwanted processing is turning this:

```md
## Examples of {&lt;componentRef&gt;}
```

Into this:

```html
<h2>Examples of {<componentRef>}</h2>
```

The browser then helpfully adds a closing tag:

```html
<h2>Examples of {<componentRef>}</componentRef</h2>
```

So a visitor to the page sees the following:

```
Examples of {}
```

### To reproduce

1. Visit https://docs.fluidproject.org/infusion/development/iocreferences.
2. Scroll down to the examples.
3. Note the weird headings.

### Expected behavior

Properly encoded `&gt;` and `&lt;` entities should be preserved in rendered HTML.

## Screenshots

Not applicable.

## Additional context or notes

Discovered while testing #230.

**Comment by Bhanu-code** [comment]
I would like to work on this, I have solved this type of issue.
