### ISSUE TITLE
remove dark circle from Infusion mug

### ISSUE THREAD

**Issue by jobara** [fluid-project/infusion-docs#234]
## Describe the bug

We're not exactly sure where it came from, but there's a dark circle on the Infusion Mug drawing that shouldn't be there.

### To reproduce
1. Go to the [landing](https://docs.fluidproject.org/infusion/development/) page

## Screenshots

<img width="545" alt="Screenshot of the Infusion Docs landing page with the Infusion Mug drawing containing a dark circle" src="https://user-images.githubusercontent.com/556024/159970417-b517b0a1-0e00-4e62-bb92-f4843097539a.png">

## Additional context or notes

New SVG image to replace the current one.

![Infusion Mug 2-11](https://user-images.githubusercontent.com/556024/159970375-b5e2cae9-ed93-4a23-b9bd-e92a8b386430.svg)

**Comment by NdagiStanley** [comment]
Happy to look into this. (If that's okay)

**Comment by jobara** [comment]
> Happy to look into this. (If that's okay)

@NdagiStanley thanks for the offer. I already submitted a PR for it, so no need.

**Comment by NdagiStanley** [comment]
> > Happy to look into this. (If that's okay)
> 
> @NdagiStanley thanks for the offer. I already submitted a PR for it, so no need.

Oh great.
